### ISSUE TITLE
No Rakefile found というエラーが出る

### ISSUE THREAD

**Issue by TomokiEmmei** [mkasa/vimplugins#1]
先生の授業でご紹介されていたので、ubuntuをインストールしてすぐに先生のvimののプラグインを入れてみたのですが、下記のエラーが表示され、snippetのような機能も動いていないように思います。
--------------------------------------------------------------------------------------------------------
cd /home/(ユーザー名)/.vim; rake
/bin/sh: 1: cd: can't cd to /home/(ユーザー名)/.vim
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
Makefile:3: recipe for target 'default' failed
make: *** [default] Error 1
--------------------------------------------------------------------------------------------------------
環境は下記のとおりです
・ubuntu18.04
・gcc 7.3
・git: 2.17.1
・rake: 12.3.1

どうぞよろしくお願い致します

**Comment by mkasa** [comment]
vim ユーザーなら `/home/(ユーザー名)/.vim` ディレクトリは（通常）存在しているかと思いますが、
ありますか？無ければ作ってから実行してみて下さい。

**Comment by TomokiEmmei** [comment]
初心者丸出しの質問にお早い回答をありがとうございます．
その後，先生のreadmeにかかれているmake周りはうまく行ったようなのですが，


vimを開始しようとすると
/home/tomoki/.janus/AsyncCommand/plugin/asynccommand.vim の処理中にエラーが検出されました:
行   27:
AsyncCommand requires vim compiled with +clientserver (see :help +clientserver)
続けるにはENTERを押すかコマンドを入力してください


と表示され，そのままenterを押すと，全体的に白っぽい画面になって，


function BufferkeyBindの処理中にエラーが検出されました
行22: 
E121: 未定義の変数です: g:os
E15: 無効な式です: g:os == "mac"

と表示されます．


（clientserverなるものを入れねばならぬのかとぐぐってみて， http://blog.bonar.jp/entry/20090308/1236527086に乗っている手順を一通りやってみたのですが，-clientserverのままで，さっぱりわからなくなってしまいました)

.janusを削除してもう一度トライし直したりとしてみてたところ，画面が白っぽいのと「function BufferkeyBindの〜」に関するエラーはなくなってたのですが，+clientserver云々のエラーは表示されたままです．

恐るべき初心者で誠に恐縮ですが，何かお心当たりがあればご教示いただけると幸いです．
どうぞよろしくお願いします．

**Comment by mkasa** [comment]
使っている vim が `clientserver` オプション付きでコンパイルされていないのが原因ですね。
ノーマルの（オプション数が少なくてプログラムが小さい） vim パッケージではなくて
（いろいろなオプションをてんこもりにした）gvim パッケージを入れて使ってみてはどうでしょうか。

**Comment by TomokiEmmei** [comment]
エラー文がでなくなりました，ご丁寧な回答本当にありがとうございました！
